### ISSUE TITLE
AMD Vulkan packages are not installed

### ISSUE THREAD

**Issue by dubigrasu** [alkazar/gamer-os#2]
On my system using an AMD card (from lspci):
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
```
I couldn't start any Vulkan games because no AMD vulkan drivers were installed.
I went with what Arch Wiki recommends:
https://wiki.archlinux.org/index.php/Vulkan#Installation
and installed the following packages:
* vulkan-icd-loader
* lib32-vulkan-icd-loader
* vulkan-radeon
* lib32-vulkan-radeon

For checking/testing vulkan I also installed:
* vulkan-tools

https://wiki.archlinux.org/index.php/Vulkan#Installation

From what I can see so far, these packages are enough to solve the issue, at least for my particular card. Maybe also vulkan-intel could be considered for Intel graphics users.

But (and this might explain it) I also want to add that my card, which is a Radeon GCN 1.0 "Southern Islands" does not use by default the amdgpu driver, but radeon, so no Vulkan support by default.
To switch the card to the amdgpu driver, it has to be enabled explicitly.
https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support
which I did in this case.

Maybe the Arch installation procedure is more fussy, sees this specific card and choose to not install the AMD Vulkan drivers since they're not needed by default, not sure here.
On the other hand (with amdgpu support enabled or not) on other distros tested so far, like SteamOS or Ubuntu, the AMD Vulkan drivers are installed regardless.

**Comment by alkazar** [comment]
Could you try installing vulkan-intel on your system, restart and make sure vulkan games still work?

I am wondering if it is safe to install them side by side. According to the Arch wiki page you linked, vulkan-intel does interfere with nvidia graphics.

Just trying to figure out if we can make do with nvidia and non-nvidia cases or if we need a third case for intel.

I am actually not even sure if gamerOS will work on intel graphics. I know I could never get SteamOS to work on intel graphics.

**Comment by alkazar** [comment]
In any case, I added the following packages to the default install:
 - vulkan-icd-loader
 - lib32-vulkan-icd-loader
 - vulkan-radeon
 - lib32-vulkan-radeon

This didn't seem to interfere with the operation of my nvidia card.

Commit: https://github.com/alkazar/gamer-os/commit/93c9e5fa7e5e15a1c62c2e9fde764003af7e2e23

@dubigrasu could you try re-installing again to see if Vulkan works for you out of the box now?

**Comment by dubigrasu** [comment]
About the previous question:
I did installed vulkan-intel alongside my existing vulkan-radeon packages, and while it does still work, I'm not so sure about being interference free.

Basically the games I tested they still work, but occasionally some of them hang inexplicably.
I removed the vulkan-intel packages and the situation apparently got back to normal, so I'm not sure what to say.
Maybe it would be more safe for the moment to **not** have vulkan-intel packages installed.

I also tested by itself my Intel graphics :
`00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)`
(I practically removed my external card) and BPM still works, but slowly, and games are even slower or crashing, but since is a pretty old chip that's not very conclusive.

About reinstalling to test the AMD Vulkan packages, sure, (although exactly out of the box Vulkan will still not work due to my GCN 1.0 card).

**Comment by dubigrasu** [comment]
OK, I did a fresh install and all the necessary AMD Vulkan packages were installed and working.

**Comment by alkazar** [comment]
Thanks for all your help. I have left out `vulkan-intel` for now.

Regarding your specific graphics card. I am not very familiar with the AMD graphics stack (it is quite confusing!), but from doing some reading I understand the problem as:
 - mesa includes both the new `amdgpu` and older `radeon` drivers
 - the `radeon` driver does not support vulkan (despite the confusingly named package `vulkan-radeon`)
 - mesa defaults to using the `radeon` driver for some specific cards (including yours) because there may be some regressions for those cards with `amdgpu`

If that is accurate, I would say I don't want to change the defaults that mesa provides. It is possible that there could be other issues when using the `amdgpu` driver with these cards. Maybe one day mesa will enable `amdgpu` by default for all cards when it is considered more tested/stable.

It does unfortunately mean that those using these generations of cards will not be able to use vulkan for now.

**Comment by dubigrasu** [comment]
It is confusing indeed, but you sum it up well.
There used to be issues with _amdgpu_ on old CGN cards in the past, yes, like HDMI sound not working or various graphical weirdness, but I haven't seen these (or heard about) since years maybe.
But yes, Mesa still defaults to _radeon_ for whatever reason, maybe some cards out there **do** exhibit issues, IDK. 
So I guess the risk does exists, that someone somewhere is having a CGN 1.0 card that doesn't play well with _amdgpu_, for which defaulting to _radeon_ is the sensible choice.

Maybe an optional _install.sh_ with _amdgpu_ enabled could exist for these cards, or just a choice in the installer:
"You have a CGN 1.0 AMD card, do you want to enable amdgpu? Y/N"

**Comment by alkazar** [comment]
@dubigrasu there was some big changes made to the detection and configuration of amd gpus. Could you test the latest master branch to see if things are setup correctly for you by default now? Thanks!

**Comment by dubigrasu** [comment]
The installation went as usual except the GPU detection part, where my GPU was detected as a legacy one:
```
lspci: Unable to load libkmod resources: error -12
Legacy AMD/ATI GPU detected, installing drivers...
```
And it went on and installed only xf86-video-ati, mesa-vdpau and lib32-mesa-vdpau.

But before actually executing the _install.sh_, I did checked manually with:
`lspci | grep -E -i '(vga|3d|display)' | grep -i amd`
also:
`lspci -nnk | grep -i vga -A3 | grep 'Kernel modules: radeon, amdgpu'`

and the output seemed OK:
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]`
respectively:
`Kernel modules: radeon, amdgpu`

Also, after the reboot I downloaded again the _install.sh_ script, edited it and executed only the GPU detection section (basically kept the lines 95 >142), and this time the GPU was correctly detected and the appropriate packages installed, log here: 
[gpu.log](https://github.com/alkazar/gamer-os/files/3033709/gpu.log)
This is the actual shell used:
[install_edited.sh.txt](https://github.com/alkazar/gamer-os/files/3033742/install_edited.sh.txt)


So the GPU detection section works basically fine, but not from within the initial installer.

**Comment by alkazar** [comment]
Investigated a little bit and found that `lspci -nnk` does not output the kernel modules line when run from inside the arch chroot. That is what the `libkmod resources` error is about. An easy work around is to do the detection from outside the chroot and record the results for use later.

**Comment by alkazar** [comment]
@dubigrasu  could you test the `gpu-detection-fix` branch? I believe I have fixed the issue, but would like confirmation from an AMD user. Thanks!

**Comment by dubigrasu** [comment]
Yes, is working now.
I could see during the installation the message:
"AMD graphics card with radeon kernel module detected, switching kernel module and installing drivers..." 

After the reboot I could install and play right away a couple of SteamPlay/Proton games using Vulkan, and some native ones also using Vulkan without issues.
AFAICT this issue is solved. Good job.

**Comment by alkazar** [comment]
@dubigrasu great, thanks for testing!

**Comment by mwprado** [comment]
Is there a way to test if I had a vulkan driver I stalled? I believe that something is wrong. After proton 5, vulkan is default enable andI have to disable using PROTON_USE_WINED3D=1.
I have a radeon pro wx4100 .

**Comment by mwprado** [comment]
> 
> 
> Is there a way to test if I had a vulkan driver I installed? I believe that something is wrong. After proton 5, vulkan is default enable andI have to disable using PROTON_USE_WINED3D=1.
> I have a radeon pro wx4100 .

I found the system was loading intel vulkan drivers. I delete intel ico files and the system is workingo with amd vulkan drivers
