### ISSUE TITLE
Missing pulseaudio-alsa package causing issues for games running through SteamPlay/Proton.

### ISSUE THREAD

**Issue by dubigrasu** [alkazar/gamer-os#8]
On a fresh install almost all games I tried with SteamPlay/Proton are having issues, specifically not starting or hanging at various points, crashing or at best starting without audio.
Installing the `pulseaudio-alsa` package fixes this.

Two example games that consistently are having these issues are RIME and Narcosis.

**Comment by alkazar** [comment]
hmm... in my testing I didn't encounter issues, however this package seems like it would be necessary. I have added it in 0ea13617f4a1ef0a1211f28eae6c69f50a961d47

Thanks for reporting!
